name: First GitHub Actions Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Print Welcome Message
        run: echo "Welcome to GitHub Actions!"
